services:
    # Development service
    web-dev:
        container_name: web_dev
        build:
            context: .
            dockerfile: docker/Dockerfile.dev
        ports:
            - '3000:3000'
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        depends_on:
            - db

    # Production service
    web-prod:
        container_name: web_prod
        build:
            context: .
            dockerfile: docker/Dockerfile.prod
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
        depends_on:
            - db

    # Database service
    db:
        image: mysql:8.0
        container_name: db_facultades
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
            MYSQL_DATABASE: ${DB_DATABASE:-db_facultades}
            MYSQL_USER: ${DB_USER:-user_facultades}
            MYSQL_PASSWORD: ${DB_PASSWORD:-password}
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql
            - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        command: --default-authentication-plugin=mysql_native_password
        restart: always

volumes:
    mysql_data:
